picks = {'week1': {'chinos': 'large blue top',
           'new brown trouser': ['silk plain black top',
                                 'orange and white top'],
           'soft light blue jeans': ['rough plain black top',
                                     'orange and white top']},
 'week2': {'big black striped trouser': 'orange and white longsleeve top',
           'big plain blue trousers': ['clear white top',
                                       'rough plain black top'],
           'soft light blue jeans': ['large blue top', 'striped blue shirt']},
 'week3': {'new brown trouser': 'rough plain black top',
           'old brown trouser': ['orange and white top',
                                 'silk plain black top'],
           'white juggers': ['clear white top', 'large blue top']}}
